-- ============================================================
-- 003_seed_education.sql
-- Run this THIRD in the Supabase SQL Editor
-- Seeds 8 education modules with 50+ questions
-- ============================================================

-- ============================================================
-- MODULE 1: Introduction to Gold Trading
-- ============================================================
INSERT INTO education_modules (id, title, description, order_index, difficulty, estimated_minutes) VALUES
('mod-001-0000-0000-000000000001', 'Introduction to Gold Trading', 'Learn the fundamentals of gold (XAU/USD) trading, why gold moves, and how to read basic price action.', 1, 'beginner', 20);

INSERT INTO education_questions (module_id, question, question_type, options, correct_answer, explanation, order_index) VALUES
('mod-001-0000-0000-000000000001', 'What does XAU/USD represent?', 'multiple_choice', '["Gold vs US Dollar", "Silver vs US Dollar", "Gold vs Euro", "Platinum vs US Dollar"]', 'Gold vs US Dollar', 'XAU is the ISO currency code for gold. XAU/USD means the price of one troy ounce of gold in US dollars.', 1),
('mod-001-0000-0000-000000000001', 'Gold is considered a "safe haven" asset.', 'true_false', NULL, 'true', 'Gold is widely considered a safe haven because investors buy it during times of economic uncertainty, geopolitical risk, or market volatility.', 2),
('mod-001-0000-0000-000000000001', 'What happens to gold prices when the US Dollar strengthens?', 'multiple_choice', '["Gold prices rise", "Gold prices fall", "Gold prices stay flat", "No relationship exists"]', 'Gold prices fall', 'Gold and the US Dollar have an inverse relationship. When USD strengthens, gold becomes more expensive for foreign buyers, reducing demand and lowering prices.', 3),
('mod-001-0000-0000-000000000001', 'The Federal Reserve interest rate decisions can impact gold prices.', 'true_false', NULL, 'true', 'Higher interest rates increase the opportunity cost of holding gold (which pays no yield), typically pushing gold prices lower. Lower rates are bullish for gold.', 4),
('mod-001-0000-0000-000000000001', 'What is a "troy ounce" in gold trading?', 'tap_reveal', NULL, 'A troy ounce equals 31.1035 grams. It is the standard unit of measurement for precious metals like gold and silver. It is slightly heavier than a regular (avoirdupois) ounce which is 28.35 grams.', 'Gold is priced per troy ounce on global exchanges. XAU/USD shows the price of one troy ounce in US dollars.', 5),
('mod-001-0000-0000-000000000001', 'Which of these is the largest gold futures exchange?', 'multiple_choice', '["London Metal Exchange (LME)", "COMEX (CME Group)", "Tokyo Commodity Exchange", "Shanghai Gold Exchange"]', 'COMEX (CME Group)', 'COMEX (part of CME Group in Chicago) is the world''s leading gold futures exchange. It is the primary price discovery venue for gold globally.', 6),
('mod-001-0000-0000-000000000001', 'Inflation typically causes gold prices to increase.', 'true_false', NULL, 'true', 'Gold is historically used as an inflation hedge. When fiat currencies lose purchasing power due to inflation, gold tends to hold or increase its value.', 7);

-- ============================================================
-- MODULE 2: Reading Price Action & Candlesticks
-- ============================================================
INSERT INTO education_modules (id, title, description, order_index, difficulty, estimated_minutes) VALUES
('mod-002-0000-0000-000000000002', 'Reading Price Action & Candlesticks', 'Master Japanese candlestick patterns and understand how to read price action for gold trading signals.', 2, 'beginner', 25);

INSERT INTO education_questions (module_id, question, question_type, options, correct_answer, explanation, order_index) VALUES
('mod-002-0000-0000-000000000002', 'What does a bullish engulfing candlestick pattern signal?', 'multiple_choice', '["A potential reversal to the downside", "A potential reversal to the upside", "A continuation of the downtrend", "No significant signal"]', 'A potential reversal to the upside', 'A bullish engulfing pattern forms when a large green candle completely engulfs the previous red candle''s body, signaling buyers have overwhelmed sellers — a potential bullish reversal.', 1),
('mod-002-0000-0000-000000000002', 'A Doji candlestick represents market indecision.', 'true_false', NULL, 'true', 'A Doji has a very small body (open and close are nearly equal), showing neither buyers nor sellers are in control. It often signals a potential reversal, especially after a strong trend.', 2),
('mod-002-0000-0000-000000000002', 'What is the "wick" (or shadow) of a candle?', 'tap_reveal', NULL, 'The wick (also called a shadow or tail) is the thin line extending above or below the candle body. The upper wick shows the highest price reached during that period. The lower wick shows the lowest price. Long wicks indicate price rejection at that level.', 'Long upper wicks on gold candles often signal sellers rejecting higher prices — a bearish sign. Long lower wicks signal buyers rejecting lower prices — a bullish sign.', 3),
('mod-002-0000-0000-000000000002', 'A "pin bar" candlestick has a long body and very short wicks.', 'true_false', NULL, 'false', 'A pin bar (also called a hammer or shooting star) has a SMALL body and a LONG wick. The long wick represents strong price rejection at that level.', 4),
('mod-002-0000-0000-000000000002', 'Which candlestick pattern suggests strong bullish momentum?', 'multiple_choice', '["Evening Star", "Bearish Harami", "Three White Soldiers", "Dark Cloud Cover"]', 'Three White Soldiers', 'Three White Soldiers is a bullish pattern consisting of three consecutive long green candles, each opening within the body of the previous candle and closing near its high — showing sustained buying pressure.', 5),
('mod-002-0000-0000-000000000002', 'What timeframe is most commonly used for gold day trading entry signals?', 'multiple_choice', '["Monthly", "Weekly", "15-minute or 1-hour", "1-minute"]', '15-minute or 1-hour', 'Day traders typically use higher timeframes (Daily, 4H) for trend analysis and enter on lower timeframes (15m, 1H) for precision entries with tight stop losses.', 6),
('mod-002-0000-0000-000000000002', 'An "inside bar" forms when today''s range is completely within the previous bar''s range.', 'true_false', NULL, 'true', 'An inside bar represents consolidation and indecision. A breakout from an inside bar often leads to a strong directional move, especially when it forms at key support/resistance levels.', 7);

-- ============================================================
-- MODULE 3: Support & Resistance Levels
-- ============================================================
INSERT INTO education_modules (id, title, description, order_index, difficulty, estimated_minutes) VALUES
('mod-003-0000-0000-000000000003', 'Support & Resistance Levels', 'Learn how to identify and trade key support and resistance zones in the gold market.', 3, 'beginner', 30);

INSERT INTO education_questions (module_id, question, question_type, options, correct_answer, explanation, order_index) VALUES
('mod-003-0000-0000-000000000003', 'When price breaks through a resistance level, what often happens?', 'multiple_choice', '["It remains resistance forever", "It becomes a new support level", "Price immediately reverses", "The level becomes irrelevant"]', 'It becomes a new support level', 'This is called "role reversal" — a former resistance level, once broken, often becomes the new support. This is because traders who missed the breakout buy on the pullback to that level.', 1),
('mod-003-0000-0000-000000000003', 'Round numbers (like $2000, $2100) often act as psychological support/resistance for gold.', 'true_false', NULL, 'true', 'Round numbers attract large stop-loss clusters and option barriers. Market makers are aware of these levels, creating self-fulfilling support/resistance at psychological price points.', 2),
('mod-003-0000-0000-000000000003', 'What makes a support or resistance level "stronger"?', 'tap_reveal', NULL, 'A level is stronger when: (1) price has tested it multiple times, (2) significant volume traded at that level, (3) it aligns with round numbers, (4) it corresponds to daily/weekly highs or lows, (5) multiple timeframes show the same level. The more confluences, the stronger the level.', 'For gold, the strongest levels are often weekly or monthly highs/lows that have been tested 3+ times with significant volume.', 3),
('mod-003-0000-0000-000000000003', 'It is best to place your stop loss exactly AT the support level.', 'true_false', NULL, 'false', 'Placing stops exactly at support/resistance is risky because market makers often "sweep" these obvious levels. Place stops a few pips BEYOND the level to avoid stop hunts.', 4),
('mod-003-0000-0000-000000000003', 'What is a "liquidity sweep" or "stop hunt"?', 'multiple_choice', '["A broker error", "When price briefly moves beyond a key level to trigger stops before reversing", "A government intervention", "A trading strategy for beginners"]', 'When price briefly moves beyond a key level to trigger stops before reversing', 'Institutional traders often push price beyond obvious support/resistance to trigger retail stop losses, generating liquidity to fill their large orders. This is why we often see "fake breakouts."', 5),
('mod-003-0000-0000-000000000003', 'The Daily high and low are important support/resistance levels to watch.', 'true_false', NULL, 'true', 'Daily highs and lows represent the extremes where buyers and sellers were active. These levels are widely watched by institutional traders and often act as strong support/resistance.', 6),
('mod-003-0000-0000-000000000003', 'How should you draw support/resistance zones?', 'multiple_choice', '["As a single precise price line", "As a zone/range of prices to account for wicks and spreads", "Only at round numbers", "Using the close price only"]', 'As a zone/range of prices to account for wicks and spreads', 'Price rarely respects a single pixel-perfect line. Drawing zones (boxes) that encompass the cluster of wicks and candle bodies gives a more realistic and effective trading area.', 7);

-- ============================================================
-- MODULE 4: Risk Management Fundamentals
-- ============================================================
INSERT INTO education_modules (id, title, description, order_index, difficulty, estimated_minutes) VALUES
('mod-004-0000-0000-000000000004', 'Risk Management Fundamentals', 'The most important skill in trading — learn how to protect your capital and size positions correctly.', 4, 'intermediate', 35);

INSERT INTO education_questions (module_id, question, question_type, options, correct_answer, explanation, order_index) VALUES
('mod-004-0000-0000-000000000004', 'What is the recommended maximum risk per trade for most retail traders?', 'multiple_choice', '["10-20% of account", "5-10% of account", "1-2% of account", "50% of account"]', '1-2% of account', 'The professional standard is to risk 1-2% of your total account per trade. This allows you to sustain 50+ losing trades before losing your account, giving you statistical edge to recover.', 1),
('mod-004-0000-0000-000000000004', 'A higher lot size always means higher profits.', 'true_false', NULL, 'false', 'Higher lot sizes mean higher potential profits AND losses. Trading with oversized positions is the #1 cause of blown accounts. Proper position sizing is critical.', 2),
('mod-004-0000-0000-000000000004', 'What is the formula for calculating position size?', 'tap_reveal', NULL, 'Position Size = (Account Balance × Risk %) ÷ (Stop Loss in Pips × Pip Value)\n\nExample: $10,000 account, 1% risk = $100 risk. Stop loss = 20 pips. Pip value on XAU/USD 0.01 lot ≈ $0.10.\nSo: $100 ÷ (20 × $10 per pip for standard lot) = 0.5 lots.\n\nAlways calculate before every trade.', 'Most brokers have a built-in lot size calculator. Never guess your position size.', 3),
('mod-004-0000-0000-000000000004', 'What is a "Risk:Reward Ratio" (RRR)?', 'multiple_choice', '["The ratio of your wins to losses", "The ratio of potential profit to potential loss on a trade", "Your account balance vs margin", "The number of pips risked vs won"]', 'The ratio of potential profit to potential loss on a trade', 'RRR compares how much you risk vs how much you stand to gain. A 1:2 RRR means you risk $50 to potentially gain $100. Minimum recommended RRR for gold trading is 1:1.5 or higher.', 4),
('mod-004-0000-0000-000000000004', 'You can be profitable with a 40% win rate if your average win is larger than your average loss.', 'true_false', NULL, 'true', 'With a 1:3 RRR, you only need to win 25% of trades to break even. With 40% wins and 1:3 RRR, you are very profitable. This is why risk:reward matters more than win rate alone.', 5),
('mod-004-0000-0000-000000000004', 'What should you do when a trade hits your stop loss?', 'multiple_choice', '["Average down and add more", "Accept the loss and move to the next setup", "Remove the stop loss to give it more room", "Double your position size next trade"]', 'Accept the loss and move to the next setup', 'A stop loss is a predetermined exit point. Moving it or averaging down is "hope trading" — the most dangerous habit a trader can develop. Accept losses as the cost of doing business.', 6),
('mod-004-0000-0000-000000000004', 'A "drawdown" refers to the maximum loss from a peak in your account equity.', 'true_false', NULL, 'true', 'Drawdown measures how far your account has fallen from its highest point. Professional traders aim to keep maximum drawdowns below 20%. A 50% drawdown requires a 100% gain just to break even.', 7);

-- ============================================================
-- MODULE 5: Trading Sessions & Market Hours
-- ============================================================
INSERT INTO education_modules (id, title, description, order_index, difficulty, estimated_minutes) VALUES
('mod-005-0000-0000-000000000005', 'Trading Sessions & Market Hours', 'Understand when gold markets are most active and how different sessions affect volatility and opportunity.', 5, 'intermediate', 20);

INSERT INTO education_questions (module_id, question, question_type, options, correct_answer, explanation, order_index) VALUES
('mod-005-0000-0000-000000000005', 'Which session typically has the highest gold volatility?', 'multiple_choice', '["Asian Session", "London Session", "New York Session", "London/NY Overlap"]', 'London/NY Overlap', 'The London/New York overlap (8am-12pm EST) is the most volatile period for gold. Both major financial centers are active simultaneously, creating the highest volume and largest price moves.', 1),
('mod-005-0000-0000-000000000005', 'The Asian session (Tokyo) tends to have lower gold volatility than the London session.', 'true_false', NULL, 'true', 'Asia has less gold-specific activity. Most gold moves are driven by USD news, which is primarily during London and New York sessions. Asian session often consolidates or ranges.', 2),
('mod-005-0000-0000-000000000005', 'What time does the London session open? (EST)', 'multiple_choice', '["3:00 AM", "5:00 AM", "8:00 AM", "10:00 AM"]', '3:00 AM', 'The London session opens at 3:00 AM Eastern Standard Time (EST), or 8:00 AM GMT. This is when European institutions begin trading and often sets the directional bias for the day.', 3),
('mod-005-0000-0000-000000000005', 'US Non-Farm Payrolls (NFP) data rarely moves gold prices significantly.', 'true_false', NULL, 'false', 'NFP is one of the most market-moving events for gold. A strong jobs report typically strengthens USD and weakens gold. A weak report weakens USD and boosts gold. NFP creates some of the largest gold moves of any month.', 4),
('mod-005-0000-0000-000000000005', 'What is the "Kill Zone" in gold trading?', 'tap_reveal', NULL, 'The "Kill Zone" refers to the high-probability entry windows identified by many professional gold traders:\n\n• Asian Session KZ: 8:00 PM – 10:00 PM EST\n• London Open KZ: 2:00 AM – 5:00 AM EST\n• New York Open KZ: 7:00 AM – 9:00 AM EST\n\nThese windows align with institutional order flow activity and provide the best risk:reward entries.', 'Many AIOV Capital signals are generated during these Kill Zone windows when institutional order flow is most predictable.', 5),
('mod-005-0000-0000-000000000005', 'Friday afternoon (New York session close) is generally a good time to hold large positions overnight.', 'true_false', NULL, 'false', 'Friday afternoon positions carry weekend gap risk. Markets reopen Sunday with potentially large gaps if major news occurred over the weekend. Most professional traders reduce or close positions before Friday close.', 6),
('mod-005-0000-0000-000000000005', 'Which US economic event has the most consistent impact on gold?', 'multiple_choice', '["US Factory Orders", "Federal Reserve Interest Rate Decision", "US Housing Starts", "US ISM Manufacturing"]', 'Federal Reserve Interest Rate Decision', 'The Fed Rate Decision is the single most impactful scheduled event for gold. It directly affects USD strength, real yields, and inflation expectations — all of which drive gold prices.', 7);

-- ============================================================
-- MODULE 6: Technical Analysis Tools
-- ============================================================
INSERT INTO education_modules (id, title, description, order_index, difficulty, estimated_minutes) VALUES
('mod-006-0000-0000-000000000006', 'Technical Analysis Tools', 'Learn to use moving averages, RSI, MACD, and Fibonacci levels to identify high-probability trade setups.', 6, 'intermediate', 40);

INSERT INTO education_questions (module_id, question, question_type, options, correct_answer, explanation, order_index) VALUES
('mod-006-0000-0000-000000000006', 'What does the RSI (Relative Strength Index) measure?', 'multiple_choice', '["Volume at each price level", "The speed and magnitude of recent price changes (0-100)", "Moving average crossovers", "Support and resistance levels"]', 'The speed and magnitude of recent price changes (0-100)', 'RSI oscillates between 0-100 and measures momentum. Values above 70 suggest overbought conditions (potential reversal down). Values below 30 suggest oversold conditions (potential reversal up).', 1),
('mod-006-0000-0000-000000000006', 'When the 50 EMA is above the 200 EMA, gold is considered to be in a long-term uptrend.', 'true_false', NULL, 'true', 'The 50/200 EMA crossover is the classic "Golden Cross" (bullish) and "Death Cross" (bearish). When the faster 50 EMA crosses above the slower 200 EMA, it signals a long-term bullish trend.', 2),
('mod-006-0000-0000-000000000006', 'What is the most important Fibonacci retracement level?', 'multiple_choice', '["23.6%", "38.2%", "61.8%", "100%"]', '61.8%', 'The 61.8% level (the "Golden Ratio") is considered the most significant Fibonacci level. It represents the classic pullback level in a healthy trend where institutional buyers often re-enter.', 3),
('mod-006-0000-0000-000000000006', 'MACD (Moving Average Convergence Divergence) measures the relationship between two exponential moving averages.', 'true_false', NULL, 'true', 'MACD plots the difference between the 12-period and 26-period EMAs (MACD line), smoothed by a 9-period EMA (signal line). Crossovers and divergences provide trade signals.', 4),
('mod-006-0000-0000-000000000006', 'What does "RSI divergence" mean?', 'tap_reveal', NULL, 'RSI Divergence occurs when price and RSI move in OPPOSITE directions:\n\n• Bullish Divergence: Price makes LOWER lows, but RSI makes HIGHER lows → momentum is increasing, potential upward reversal incoming.\n\n• Bearish Divergence: Price makes HIGHER highs, but RSI makes LOWER highs → momentum is weakening, potential downward reversal incoming.\n\nDivergence is one of the strongest signals in technical analysis.', 'Gold often shows RSI divergence at major turning points. Always confirm with price action before entering.', 5),
('mod-006-0000-0000-000000000006', 'Moving averages are leading indicators that predict future price.', 'true_false', NULL, 'false', 'Moving averages are LAGGING indicators — they are calculated from historical price data. They show trend direction but lag behind current price. Leading indicators try to predict future moves (like RSI, MACD histogram).', 6),
('mod-006-0000-0000-000000000006', 'Which volume-based tool helps identify whether a trend is supported by strong buying or selling?', 'multiple_choice', '["Fibonacci Tool", "On-Balance Volume (OBV)", "Bollinger Bands", "Parabolic SAR"]', 'On-Balance Volume (OBV)', 'OBV adds volume on up days and subtracts it on down days. Rising OBV confirms an uptrend has strong buying volume behind it. Divergence between price and OBV often warns of trend reversals.', 7);

-- ============================================================
-- MODULE 7: Advanced Trade Management
-- ============================================================
INSERT INTO education_modules (id, title, description, order_index, difficulty, estimated_minutes) VALUES
('mod-007-0000-0000-000000000007', 'Advanced Trade Management', 'Learn professional techniques for managing open trades including breakeven, partial closes, and trailing stops.', 7, 'advanced', 35);

INSERT INTO education_questions (module_id, question, question_type, options, correct_answer, explanation, order_index) VALUES
('mod-007-0000-0000-000000000007', 'What does "moving to breakeven" mean in trade management?', 'multiple_choice', '["Closing half the position", "Moving the stop loss to your entry price", "Taking profit at 1:1 RRR", "Adding to your position"]', 'Moving the stop loss to your entry price', 'Moving to breakeven means placing your stop loss exactly at your entry price. This eliminates risk of loss on the trade. Professional traders typically move to breakeven once a trade has moved 1:1 in their favor.', 1),
('mod-007-0000-0000-000000000007', 'A "partial close" involves closing a portion of your position while leaving the rest running.', 'true_false', NULL, 'true', 'Partial closes allow you to secure profit at target 1 (TP1) while letting remaining position run to target 2 (TP2) or beyond. This locks in profit while maintaining exposure to larger potential moves.', 2),
('mod-007-0000-0000-000000000007', 'What is a trailing stop loss?', 'tap_reveal', NULL, 'A trailing stop moves with price as it goes in your favor, locking in profit while allowing the trade to continue running.\n\nExample: You set a 30-pip trailing stop on a buy trade.\n• Gold rises 30 pips → stop moves to entry (breakeven)\n• Gold rises 60 pips → stop is at +30 pips (locking profit)\n• Gold reverses 30 pips → trade closes with 30 pips profit\n\nTrailing stops are excellent for trending gold moves, especially after major news.', 'During strong gold trends, trailing stops help capture larger moves without the anxiety of watching every tick.', 3),
('mod-007-0000-0000-000000000007', 'You should ALWAYS take the full position size from the start of a trade.', 'true_false', NULL, 'false', 'Some professional traders use "scaling in" — entering a partial position at first signal, then adding to it on confirmation. This reduces risk on the initial entry while allowing full exposure on confirmed moves.', 4),
('mod-007-0000-0000-000000000007', 'What is the key reason to have multiple take profit levels (TP1, TP2, TP3)?', 'multiple_choice', '["To make the trade more complicated", "To secure partial profits while remaining exposed to larger moves", "To avoid paying broker fees", "Because the market always hits all targets"]', 'To secure partial profits while remaining exposed to larger moves', 'Multiple targets allow you to: (1) secure quick profits at TP1, (2) move to breakeven, (3) let remaining position run to TP2/TP3 risk-free. This is the professional approach used by fund managers.', 5),
('mod-007-0000-0000-000000000007', 'It is psychologically healthy to check your open positions every minute.', 'true_false', NULL, 'false', 'Over-monitoring open trades leads to emotional decision-making — premature exits, second-guessing valid setups, moving stops based on fear. Set your entry, stop, and targets, then check at predetermined intervals only.', 6),
('mod-007-0000-0000-000000000007', 'What does "trade management" primarily refer to?', 'multiple_choice', '["Finding new trade setups", "Actions taken AFTER a trade is opened to manage risk and maximize profit", "Analyzing economic data", "Keeping your trading journal"]', 'Actions taken AFTER a trade is opened to manage risk and maximize profit', 'Trade management is the process of handling a trade from entry to exit. This includes: when to move to breakeven, when to take partial profits, when to trail your stop, and when to close the trade.', 7);

-- ============================================================
-- MODULE 8: Trading Psychology & Mindset
-- ============================================================
INSERT INTO education_modules (id, title, description, order_index, difficulty, estimated_minutes) VALUES
('mod-008-0000-0000-000000000008', 'Trading Psychology & Mindset', 'Master the mental game of trading — learn to control emotions, avoid common biases, and build consistency.', 8, 'advanced', 30);

INSERT INTO education_questions (module_id, question, question_type, options, correct_answer, explanation, order_index) VALUES
('mod-008-0000-0000-000000000008', 'What is "FOMO" in trading?', 'multiple_choice', '["A type of chart pattern", "Fear Of Missing Out — entering a trade late out of fear of missing the move", "A risk management strategy", "A type of market order"]', 'Fear Of Missing Out — entering a trade late out of fear of missing the move', 'FOMO causes traders to chase moves after they''ve already happened, entering at poor prices with bad risk:reward. By the time most retail traders enter, institutions are often already taking profits.', 1),
('mod-008-0000-0000-000000000008', 'Revenge trading (increasing position size after a loss to recover quickly) is a sound trading strategy.', 'true_false', NULL, 'false', 'Revenge trading is one of the most destructive habits. It combines emotional decision-making with increased risk — a recipe for accelerating losses. Always return to your standard risk after a loss.', 2),
('mod-008-0000-0000-000000000008', 'What is a "trading journal" and why is it important?', 'tap_reveal', NULL, 'A trading journal is a record of every trade you take, including:\n• Entry and exit price\n• Reason for taking the trade\n• Session and instrument\n• Emotional state during the trade\n• Lessons learned\n\nWhy it matters: It creates accountability, reveals patterns in your trading (best sessions, common mistakes, profitable setups), and accelerates improvement. Professional traders use journals religiously.', 'AIOV Capital''s Trade Tracker is your digital trading journal. Use it for every trade to identify your edge and eliminate weaknesses.', 3),
('mod-008-0000-0000-000000000008', 'The goal of every trade should be to make as much money as possible.', 'true_false', NULL, 'false', 'The goal of every trade should be to EXECUTE YOUR PLAN CORRECTLY. If you follow your rules and the trade loses, that is a good trade. If you break your rules and the trade wins by luck, that is a bad trade. Focus on process, not outcome.', 4),
('mod-008-0000-0000-000000000008', 'Which psychological bias causes traders to hold losing trades too long?', 'multiple_choice', '["Confirmation bias", "Loss aversion", "Overconfidence bias", "Recency bias"]', 'Loss aversion', 'Loss aversion (from behavioral economics) means the pain of a loss is psychologically twice as powerful as the pleasure of an equivalent gain. This causes traders to "hope" losing trades recover rather than accepting the defined stop loss.', 5),
('mod-008-0000-0000-000000000008', 'A long winning streak means your next few trades are more likely to win.', 'true_false', NULL, 'false', 'This is the "Gambler''s Fallacy." Each trade is statistically independent. A winning streak does not predict future results. Trading with this mindset causes overconfidence, oversized positions, and eventually large losses.', 6),
('mod-008-0000-0000-000000000008', 'What is "process-oriented" trading?', 'multiple_choice', '["Focusing only on P&L every day", "Evaluating success based on whether you followed your trading plan, not just on trade outcomes", "Using the most complex strategies", "Trading as many times as possible per day"]', 'Evaluating success based on whether you followed your trading plan, not just on trade outcomes', 'Process-oriented trading means: a profitable trade where you broke your rules is a failure. A losing trade where you followed every rule perfectly is a success. This mindset leads to long-term consistency and professional results.', 7);
